### ISSUE TITLE
Prototype code for Comet67P

### ISSUE THREAD

**Issue by cristiantrave** [lluiscampos/trevaling#4]
This task covers the initial infrastructure and code base for the server code

Tasks to be done:
- component infrastructure including source code, dependencies management, test execution and code coverage. DONE
- server has two dummy routes: /philae and /viewer. DONE
 - /philae saves a hello world entry into the database (not necessary to actually read any real data)
 - /viewer get returns a entries from the database
- database can be non persistent DONE
- unit test for the server funcionality DONE
- instructions in README on how to build, test, and start the server DONE

**Comment by lluiscampos** [comment]
This issue is virtually done. Only missing to fix current lint errors

**Comment by lluiscampos** [comment]
This issue is virtually done. Only missing to fix current lint errors
